In [29]:
a=[1,2,3,4,5,6,7]
print (a)

[1, 2, 3, 4, 5, 6, 7]


In [30]:
import numpy 


In [31]:
import numpy as np
b=np.array(a)

In [32]:
b

array([1, 2, 3, 4, 5, 6, 7])

In [33]:
type(b)

numpy.ndarray

In [34]:
c=np.array([1,2,3,5,5,5,5])
c

array([1, 2, 3, 5, 5, 5, 5])

In [35]:
d=np.array([1,'pawan',True])
d

array(['1', 'pawan', 'True'], dtype='<U11')

In [36]:
type(d)

numpy.ndarray

In [37]:
a=np.arange(16).reshape(2,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [38]:
a.shape


(2, 8)

In [39]:
a.reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [14]:
a.ndim

2

In [16]:
a.dtype

dtype('int32')

In [17]:
a.itemsize

4

In [18]:
a.size

16

In [21]:
height=np.array([5.55,6.12,7.4,8.40])
weight=np.array([50,60,70,80])
bmi=weight/height**2
bmi

array([1.62324487, 1.60194797, 1.27830533, 1.13378685])

In [22]:
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [23]:
a.ndim

2

In [27]:
a=np.arange(1).reshape(1,1)
a.ndim

2

In [31]:
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]],dtype=complex)
a

array([[ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j],
       [ 7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j]])

In [29]:
a.shape

(2, 6)

In [30]:
a.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [33]:
a=np.zeros((3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
a=np.ones((3,2,4))
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [16]:
a=np.empty((4,6))
a


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [40]:
a=np.arange(0,55,5)
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [42]:
a=np.linspace(0,10,10)
a

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [43]:
 a = np.arange(6)                         # 1d array
 print(a)


[0 1 2 3 4 5]


In [44]:
a.ndim

1

In [43]:
a = np.random.normal(0.0, 1.0, 5) 
a

array([ 0.83213162, -0.40348172,  0.87164091, -1.12981843, -1.06992284])

In [44]:
a = np.random.normal(0.0, 100.0, (2, 4, 3)) 
a

array([[[ -13.24033321,   68.53724094,   -7.61050365],
        [  49.2783779 , -155.12094352,  -88.69487629],
        [ -47.42165879,  -43.69255529, -164.31589854],
        [  67.76024675,  -20.42698417,   51.67842058]],

       [[ -87.48495713, -140.86062847,  -22.99534777],
        [ -33.35585613,  110.07488111,  -86.76806483],
        [ 140.17417823, -198.79720409,   23.88102116],
        [  49.3551446 ,  135.44489954,  -76.96348128]]])