In [38]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
import sklearn.metrics as sklm
from sklearn import preprocessing
import math
import sklearn.model_selection as ms
import numpy as np
import numpy.random as nr
%matplotlib inline


In [39]:
radiations_predict=pd.read_csv('/home/himanshi/Downloads/Dataset_Client_Live.csv')
radiations_predict.columns

Index(['UNIXTime', 'Data', 'Time', 'Radiation', 'Temperature', 'Pressure',
       'Humidity', 'WindDirection(Degrees)', 'Speed', 'TimeSunRise',
       'TimeSunSet'],
      dtype='object')

In [56]:
radiations_predict.shape
radiations_predict.dtypes

UNIXTime                    int64
Data                       object
Time                       object
Radiation                 float64
Temperature                 int64
Pressure                  float64
Humidity                    int64
WindDirection(Degrees)    float64
Speed                     float64
TimeSunRise                object
TimeSunSet                 object
dtype: object

In [46]:
radiations_predict

UNIXTime                   Data      Time  Radiation  Temperature  \
0      1475229326  9/29/2016 12:00:00 AM  23:55:26       1.21           48   
1      1475229023  9/29/2016 12:00:00 AM  23:50:23       1.21           48   
2      1475228726  9/29/2016 12:00:00 AM  23:45:26       1.23           48   
3      1475228421  9/29/2016 12:00:00 AM  23:40:21       1.21           48   
4      1475228124  9/29/2016 12:00:00 AM  23:35:24       1.17           48   
5      1475227824  9/29/2016 12:00:00 AM  23:30:24       1.21           48   
6      1475227519  9/29/2016 12:00:00 AM  23:25:19       1.20           49   
7      1475227222  9/29/2016 12:00:00 AM  23:20:22       1.24           49   
8      1475226922  9/29/2016 12:00:00 AM  23:15:22       1.23           49   
9      1475226622  9/29/2016 12:00:00 AM  23:10:22       1.21           49   
10     1475226323  9/29/2016 12:00:00 AM  23:05:23       1.23           49   
11     1475226025  9/29/2016 12:00:00 AM  23:00:25       1.21           49   
12     1475225720  9/29/2016 12:00:00 AM  22:55:20       1.22           49   
13     1475225419  9/29/2016 12:00:00 AM  22:50:19       1.21           50   
14     1475225131  9/29/2016 12:00:00 AM  22:45:31       1.23           50   
15     1475224823  9/29/2016 12:00:00 AM  22:40:23       1.22           50   
16     1475224519  9/29/2016 12:00:00 AM  22:35:19       1.21           50   
17     1475224222  9/29/2016 12:00:00 AM  22:30:22       1.22           50   
18     1475223919  9/29/2016 12:00:00 AM  22:25:19       1.22           50   
19     1475223622  9/29/2016 12:00:00 AM  22:20:22       1.20           50   
20     1475223322  9/29/2016 12:00:00 AM  22:15:22       1.20           50   
21     1475223021  9/29/2016 12:00:00 AM  22:10:21       1.20           50   
22     1475222720  9/29/2016 12:00:00 AM  22:05:20       1.21           50   
23     1475222426  9/29/2016 12:00:00 AM  22:00:26       1.22           50   
24     1475222120  9/29/2016 12:00:00 AM  21:55:20       1.22           50   
25     1475221832  9/29/2016 12:00:00 AM  21:50:32       1.22           50   
26     1475221528  9/29/2016 12:00:00 AM  21:45:28       1.24           50   
27     1475221220  9/29/2016 12:00:00 AM  21:40:20       1.23           50   
28     1475220921  9/29/2016 12:00:00 AM  21:35:21       1.23           50   
29     1475220621  9/29/2016 12:00:00 AM  21:30:21       1.23           50   
...           ...                    ...       ...        ...          ...   
32656  1480595104  12/1/2016 12:00:00 AM  02:25:04       1.17           42   
32657  1480594804  12/1/2016 12:00:00 AM  02:20:04       1.20           42   
32658  1480594502  12/1/2016 12:00:00 AM  02:15:02       1.18           43   
32659  1480594201  12/1/2016 12:00:00 AM  02:10:01       1.18           43   
32660  1480593902  12/1/2016 12:00:00 AM  02:05:02       1.19           43   
32661  1480593602  12/1/2016 12:00:00 AM  02:00:02       1.21           43   
32662  1480593302  12/1/2016 12:00:00 AM  01:55:02       1.20           43   
32663  1480593003  12/1/2016 12:00:00 AM  01:50:03       1.20           43   
32664  1480592701  12/1/2016 12:00:00 AM  01:45:01       1.19           43   
32665  1480592402  12/1/2016 12:00:00 AM  01:40:02       1.19           43   
32666  1480592102  12/1/2016 12:00:00 AM  01:35:02       1.21           44   
32667  1480591801  12/1/2016 12:00:00 AM  01:30:01       1.21           44   
32668  1480591503  12/1/2016 12:00:00 AM  01:25:03       1.20           44   
32669  1480591202  12/1/2016 12:00:00 AM  01:20:02       1.21           44   
32670  1480590904  12/1/2016 12:00:00 AM  01:15:04       1.21           44   
32671  1480590602  12/1/2016 12:00:00 AM  01:10:02       1.21           44   
32672  1480590303  12/1/2016 12:00:00 AM  01:05:03       1.20           44   
32673  1480590001  12/1/2016 12:00:00 AM  01:00:01       1.21           44   
32674  1480589701  12/1/2016 12:00:00 AM  00:55:01       1.21           43   
32675  1480589406  12/1/2016 12

In [51]:
#cols = ['price', 'bore', 'stroke',
#         'horsepower', 'peak_rpm']
#for column in cols:
#    auto_prices.loc[auto_prices[column] == '?', column] = np.nan
#auto_prices.dropna(axis = 0, inplace = True)
#auto_prices.shape   

NameError: name 'Radiation' is not defined

In [41]:
Features = np.array(radiations_predict[['UNIXTime','Temperature','Pressure', 'Humidity', 'Speed']])
Features[:2,:]

array([[1.47522933e+09, 4.80000000e+01, 3.04600000e+01, 5.90000000e+01,
        5.62000000e+00],
       [1.47522902e+09, 4.80000000e+01, 3.04600000e+01, 5.80000000e+01,
        3.37000000e+00]])

In [42]:
nr.seed(9988)
labels = np.array(radiations_predict['Radiation'])
indx = range(Features.shape[0])
print(indx)
indx = ms.train_test_split(indx, test_size = 40)
x_train = Features[indx[0],:]
y_train = np.ravel(labels[indx[0]])
x_test = Features[indx[1],:]
y_test = np.ravel(labels[indx[1]])
print(y_train)

range(0, 32686)
[855.12   1.19 119.48 ...   1.26 115.67 823.07]


In [43]:
lin_mod = linear_model.LinearRegression(fit_intercept = False)
lin_mod.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=None, normalize=False)

In [52]:
scaler = preprocessing.StandardScaler().fit(x_train[:,:])
x_train[:,:] = scaler.transform(x_train[:,:])
x_test[:,:] = scaler.transform(x_test[:,:])
print(x_train.shape)
x_train[:5,:]


(32646, 5)


array([[-1.09766187,  1.59581159,  1.22779679,  0.61510167,  0.46579035],
       [-0.45028761,  0.30586615,  1.41073156, -1.38543416,  0.46579035],
       [ 1.55493651, -0.66159293, -0.23568135,  0.76898905,  0.46579035],
       [-0.34706866,  0.95083887,  0.31312295, -0.23127887, -0.8233322 ],
       [-1.190608  , -0.82283611, -0.78448566,  0.76898905,  0.78950334]])

In [53]:
def print_metrics(y_true, y_predicted, n_parameters):
    ## First compute R^2 and the adjusted R^2
    r2 = sklm.r2_score(y_true, y_predicted)
    r2_adj = r2 - (n_parameters - 1)/(y_true.shape[0] - n_parameters) * (1 - r2)
    
    ## Print the usual metrics and the R^2 values
    print('Mean Square Error      = ' + str(sklm.mean_squared_error(y_true, y_predicted)))
    print('Root Mean Square Error = ' + str(math.sqrt(sklm.mean_squared_error(y_true, y_predicted))))
    print('Mean Absolute Error    = ' + str(sklm.mean_absolute_error(y_true, y_predicted)))
    print('Median Absolute Error  = ' + str(sklm.median_absolute_error(y_true, y_predicted)))
    print('R^2                    = ' + str(r2))
    print('Adjusted R^2           = ' + str(r2_adj))
   
y_score = lin_mod.predict(x_test) 
print(y_score)
print_metrics(y_test, y_score, 28) 

[ 1.95205695e+03 -1.89296743e+02  3.08017150e+02 -5.04358593e+02
 -2.39724408e+02 -8.70278016e+02  1.12633129e+02  5.59769080e+01
  5.92679518e-01  1.70801276e+02 -2.62072015e+02 -3.88499426e+02
  1.69609037e+03 -8.08739635e+02  6.27461215e+01 -7.83560487e+02
  2.79692289e+03 -4.61721617e+02 -1.93157203e+02  8.84757240e+02
  3.10844153e+02 -1.99947270e+02 -6.15393790e+02  4.20839545e+02
  4.66477788e+02 -3.01383673e+02  5.47320519e+02 -5.09189636e+02
 -3.96346319e+02 -6.94474647e+02 -2.81425831e+02  1.74803573e+03
  1.25710061e+02  5.69090299e+01 -1.34778704e+03 -1.24814381e+02
 -7.95194698e+02 -5.18986406e+02  3.35165777e+02  4.44208686e+02]
Mean Square Error      = 824714.8961494479
Root Mean Square Error = 908.138148163289
Mean Absolute Error    = 683.5303953416242
Median Absolute Error  = 515.3230212747189
R^2                    = -5.638262743659512
Adjusted R^2           = -20.574353916893415
